name: Build and Deploy Flow App

on:
  push:
    branches:
      - main # Specify the branch to trigger the workflow
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "lts/*" # Specify the Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # Add additional steps for deployment
      # For example, deploying to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The target branch for deployment
          folder: dist # The folder to deploy, adjust if your output directory differs
